package com.fndong.user;
import javax.persistence.CascadeType;
// Generated Mar 17, 2016 2:59:12 PM by Hibernate Tools 4.3.1.Final
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * UserDetails generated by hbm2java
 */
@Entity
@Table(name="user_details")
public class UserDetails implements java.io.Serializable {
	@Id
	@GeneratedValue
	@Column(name="user_detail_id")
	private Integer userDetailId;
	
	@JoinColumn(name="user_id")
	@OneToOne(cascade=CascadeType.ALL,fetch=FetchType.EAGER)
	private User user;
	
	private String address;
	
	private String poscode;

	public UserDetails() {
	}

	public UserDetails(User user) {
		this.user = user;
	}
	
	public UserDetails(String address, String poscode) {
		this.address = address;
		this.poscode = poscode;
	}
	
	public UserDetails(User user, String address, String poscode) {
		this.user = user;
		this.address = address;
		this.poscode = poscode;
	}

	public Integer getUserDetailId() {
		return this.userDetailId;
	}

	public void setUserDetailId(Integer userDetailId) {
		this.userDetailId = userDetailId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPoscode() {
		return this.poscode;
	}

	public void setPoscode(String poscode) {
		this.poscode = poscode;
	}

}
